### ISSUE TITLE
getTransactionInfo issue

### ISSUE THREAD

**Issue by bitog** [DogFive/pyCoinPayments#5] opened 2020-08-04 16:12 UTC
Hi there,

I tried to pull a transaction using `getTransactionInfo`. I used a correct TXID however it is not returning anything to me. All I get is `[]`. Any idea why that is happeing?

Thanks.

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment] 2020-08-24 05:20
Have you tried this on more than one transaction? In the past I've had intermittent issues with the API.

If you send along an example TXID, I'll give it a try.

**Comment by bitog** [comment] 2020-09-04 08:03
Yes for sure.

Try the following TXID: `CPEI48A1P31Y1N2SKCXGXKQSTF`

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment] 2021-01-24 23:59
@bitog 

Sorry about the wait. Couple of things to check here, the API key you're using might not have permissions to that API Call.

I shutoff all permissions on one of my API keys and recieved the following respone in the "Request" method of the CryptoPayments class:

`error":"This API Key does not have permission to use that command!"`


In Coinpayments go to Account > ApiKeys > Click "Edit Permissions" button for the relevant API key.


There's zero error handling for feedback for this API wrapper. Originally it was intended as a quick up start to using their API. I might spend some time updating and furthering the functionality.

**Comment by DogFive** [comment] 2021-01-25 00:45
@bitbog,

Whoops noticed a silly error regarding your issue while implementing very basic error feedback, I passed a dictionary to the getTransactionInfo function and forgot to grab the actual txid value while passing off the parameters to the URL call. So on top of checking permissions there is a small issue in the library I will fix.

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment] 2021-01-25 03:24
Should be fixed now, let me know if you have any further issues. There are breaking changes from the return of the API client, see the Readme, it now provides errors directly.

Previously the api would return a variable with fields, it now returns a python dictionary. Checking result['error'] should provide you more info if this latest commit does not immediately fix your issue.

**Closed as completed by 59adc5ed-4a64-4984-bf6a-2b9117da6625** 2021-01-25 03:24 UTC
